version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
networks:
  default:
    name: ${GLYGEN_NETWORK:-glygen-network}
    external: true
